# Generated by Django 3.0 on 2022-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
